global:
  scrape_interval:     5s
  evaluation_interval: 5s
#  external_labels:
#    monitor: 'KrakenD'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'KrakenD'
    scrape_interval: 5s
    static_configs:
      - targets: ['apigateway:9090']
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nginx-static-exporter'
    scrape_interval: 20s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['nginxexporter:9113']
  - job_name: docker
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9323']
  - job_name: microservices
    scrape_interval: 5s
    static_configs:
      - targets: ['profile:9090', 'auth:9090', 'connection:9090', 'post:9090', 'postreaction:9090', 'campaign:9090', 'monitoring:9090', 'notification:9090']