global:
  scrape_interval:     5s
  evaluation_interval: 5s
#  external_labels:
#    monitor: 'KrakenD'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'KrakenD'
    scrape_interval: 5s
    static_configs:
      - targets: ['apigateway:9090']
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
#  - job_name: app
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['host.docker.internal:10088']